### ISSUE TITLE
"why is one msat?"

### ISSUE THREAD

**Issue by Sjors** [thesimplekid/cln-nostr-connect#10]
I noticed this comment:

https://github.com/thesimplekid/cln-nostr-wallet-connect/blob/6450ad99c3ae3eabd2870c0805ff7ef8369702a3/src/main.rs#L208-L213

Can you explain what the problem is?

Should I worry? :-)

**Comment by thesimplekid** [comment]
Honestly, I don't remember likely just forgot to delete the comment. I'll double check though

**Comment by thesimplekid** [comment]
They all should have been msats. I changed here for it to be sats. Im gonna rewrite this plugin over the weekend with a few other improvements but main has the quick fix for that

[9369b18](https://github.com/thesimplekid/cln-nostr-wallet-connect/commit/9369b18e33f7d3850f8c20869dd899f1bc752b42)
