### ISSUE TITLE
Can't connect to my own relay + where does .config disappear to?

### ISSUE THREAD

**Issue by IngwiePhoenix** [thesimplekid/cln-nostr-connect#5]
Hello!

I wanted to set this up to pay zaps on Snort, however this didn't go very well:

```
2023-07-27T10:40:28.443Z INFO    plugin-cln-nostr-wallet-connect: Nostr Wallet Connect Config: \"/.config/cln-nostr-wallet-connect/config\"
2023-07-27T10:40:28.444Z INFO    plugin-cln-nostr-wallet-connect: No private key provided, creating new identity
2023-07-27T10:40:28.445Z INFO    plugin-cln-nostr-wallet-connect: nostr+walletconnect://(redacted)
2023-07-27T10:40:28.502Z **BROKEN** plugin-cln-nostr-wallet-connect: Impossible to connect to wss://relay.ingwie.me/: ws error: IO error: received fatal alert: InternalError
```

This is odd for two reasons:

1. `wss://relay.ingwie.me` has a valid certificate and is running. Looking at my logs, I can actually tell that it is quite busy and used by more than myself.
2. `/.config`? That path is not writeable by the user running C-Lightning; in fact it should only have access to it's home at `/usb/c-lightning`.

Can you help me figure this out? I disabled the plugin for now.

Thanks a lot and kind regards,
Ingwie

**Comment by thesimplekid** [comment]
Hey,

> /.config? That path is not writeable by the user running C-Lightning; in fact it should only have access to it's home at /usb/c-lightning.

I thought I added this option before but I guess not  21b6def7bf509a57168c6aa76c23ec3295862a4c. If you pull main you can now set the config path in the cln_config file using the `nostr_connect_config_path` option. 

> wss://relay.ingwie.me has a valid certificate and is running. Looking at my logs, I can actually tell that it is quite busy and used by more than myself.

Is this a public relay that I should be able to access? I can't with snort or [nostr-tool](https://github.com/0xtrr/nostr-tool). Seems to be an SSL error of some sort. Is it a self-signed cert?

**Comment by IngwiePhoenix** [comment]
No, it's a Let's Encrypt cert, I use Caddy as my webserver. But I will restart it, maybe something went wrong there? Wouldn't know what, though.

**Comment by IngwiePhoenix** [comment]
Turns out the invalid cert was because at some point I changed my config and forgot about it...impressive derp on my end. The relay should now be reachable once again.

I am recompiling freshly pulled main to see if it now works as expected.

**Comment by IngwiePhoenix** [comment]
Connection works now and the added config value works as well!

Thanks for your support ^.^

**Comment by thesimplekid** [comment]
Glad you got it working, let me know if you run into any issues
