### ISSUE TITLE
Kill msat?

### ISSUE THREAD

**Issue by Sjors** [thesimplekid/cln-nostr-connect#9]
I find msat amounts confusing and useless for the purpose of a maximum budget. They just make it easier to add a few too many zeros.

Changing to sat would be a breaking change though, maybe not worth it if too many people already use the plugin.

**Comment by thesimplekid** [comment]
It could be done in a none breaking way by adding an optional argument. `limit_sat`.  However, I don't think many are using the plugin so a breaking change would probably fine. 

https://github.com/thesimplekid/cln-nostr-wallet-connect/blob/6450ad99c3ae3eabd2870c0805ff7ef8369702a3/src/main.rs#L36-L43

**Comment by thesimplekid** [comment]
killed

[9369b18](https://github.com/thesimplekid/cln-nostr-wallet-connect/commit/9369b18e33f7d3850f8c20869dd899f1bc752b42)
